apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: ktt-nginx-webserver
spec:
  containers:
  - name:  demoncontainer
    image: nginx
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"



