apiVersion: v1
kind: Pod   
metadata:
  name: secret-env
spec:
  containers:
  - name: secret-env 
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:                
        secretKeyRef:
         name: ktt-k8-secret
         key: dbpass

  restartPolicy: Never
